%% 
% Code on regular grid.

disp('Compiling anisoVoronoi2Diterative.');
mex grid/anisoVoronoi2Diterative.cpp

%%
% Code Domain meshing.

disp('Compiling anisoFPMeshing2Diterative.');
mex domain/anisoFPMeshing2Diterative.cpp

%% 
% Code FM isotropic 

mex fast-marching/perform_front_propagation_2d.cpp fast-marching/perform_front_propagation_2d_mex.cpp fast-marching/fheap/fib.cpp 
mex fast-marching/perform_front_propagation_3d.cpp fast-marching/perform_front_propagation_3d_mex.cpp  fast-marching/fheap/fib.cpp 


%%
% Code skeleton.

mex skeleton/skeleton.cpp

%%
% Code on mesh grid.

basep = 'mesh/';
disp('Compiling EikonalSolverMesh, might time some time.');
files =  { ...
    'AnisoEikonalSolverMesh.cpp', ...
    'gw/gw_core/GW_Config.cpp',           ...
    'gw/gw_core/GW_FaceIterator.cpp',     ...
    'gw/gw_core/GW_SmartCounter.cpp',     ...
    'gw/gw_core/GW_VertexIterator.cpp',   ...
    'gw/gw_core/GW_Face.cpp',             ...
    'gw/gw_core/GW_Mesh.cpp',             ...
    'gw/gw_core/GW_Vertex.cpp',           ...
    'gw/gw_geodesic/GW_GeodesicFace.cpp', ...                                              
    'gw/gw_geodesic/GW_GeodesicMesh.cpp',     ...                                 
    'gw/gw_geodesic/GW_GeodesicPath.cpp',         ...                       
    'gw/gw_geodesic/GW_GeodesicPoint.cpp',            ...           
    'gw/gw_geodesic/GW_TriangularInterpolation_Cubic.cpp', ...      
    'gw/gw_geodesic/GW_GeodesicVertex.cpp',                    ...  
    'gw/gw_geodesic/GW_TriangularInterpolation_Linear.cpp',      ...
    'gw/gw_geodesic/GW_TriangularInterpolation_Quadratic.cpp',  ...
};
str = 'mex '; % -v
for i=1:length(files)
    str = [str basep files{i} ' '];
end
eval(str);

%% Connectivity matlab
basep = 'mesh/';
disp('Compiling ComputeMeshConnectivity, might time some time.');
files =  { ...
    'ComputeMeshConnectivity.cpp', ...
    'gw/gw_core/GW_Config.cpp',           ...
    'gw/gw_core/GW_FaceIterator.cpp',     ...
    'gw/gw_core/GW_SmartCounter.cpp',     ...
    'gw/gw_core/GW_VertexIterator.cpp',   ...
    'gw/gw_core/GW_Face.cpp',             ...
    'gw/gw_core/GW_Mesh.cpp',             ...
    'gw/gw_core/GW_Vertex.cpp',           ...
    'gw/gw_geodesic/GW_GeodesicFace.cpp', ...                                              
    'gw/gw_geodesic/GW_GeodesicMesh.cpp',     ...                                 
    'gw/gw_geodesic/GW_GeodesicPath.cpp',         ...                       
    'gw/gw_geodesic/GW_GeodesicPoint.cpp',            ...           
    'gw/gw_geodesic/GW_TriangularInterpolation_Cubic.cpp', ...      
    'gw/gw_geodesic/GW_GeodesicVertex.cpp',                    ...  
    'gw/gw_geodesic/GW_TriangularInterpolation_Linear.cpp',      ...
    'gw/gw_geodesic/GW_TriangularInterpolation_Quadratic.cpp',  ...
};
str = 'mex -v ';
for i=1:length(files)
    str = [str basep files{i} ' '];
end
eval(str)
%% Code on mesh grid with matlab connectivity
basep = 'mesh/';
disp('Compiling AnisoEikonalSolverMatlabMesh, might take no time :-P.');
files =  { ...
    'AnisoEikonalSolverMatlabMesh.cpp'

};
str = 'mex '; % -v
for i=1:length(files)
    str = [str basep files{i} ' '];
end
eval(str);